# Generated by Django 4.1.4 on 2023-02-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('country', models.CharField(choices=[('US', 'United States'), ('RU', 'Russia'), ('KG', 'Kyrgyzstan'), ('KZ', 'Kazakhastan')], max_length=300)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=55)),
            ],
        ),
    ]
