# Generated by Django 4.1.6 on 2023-02-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('RU', 'Russia'), ('KG', 'Kyrgyzstan'), ('KZ', 'Kazakhastan')], max_length=300),
        ),
    ]
