# Generated by Django 4.1.4 on 2023-02-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('tagline', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
