# Generated by Django 4.1.6 on 2023-02-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('git_hub', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('resume', models.FileField(blank=True, upload_to='')),
                ('about_us', models.TextField(choices=[(1, 'from media'), (2, 'sarafannor radio'), (3, 'other')])),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
    ]
